title: 5 Important Coding Scripts for Research Analysis 
description: Whether you have invested years into statistics, or just dipping your toes into a future career, coding for research projects can get messy. Here are some tips that helped me get organized.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman