title: Statistics and Data Science Projects
description: Organized summaries of Jackson Passey's projects and blog posts
email: jxnpass@gmail.com

github:
  is_project_page: true
  owner_url: https://github.com/jxnpass
  owner_name: Jackson Passey

google_analytics: GTM-5WMP23X4
theme: jekyll-theme-cayman

collections:
  tags:
    output: true
    permalink: /topics/:name/
