title: 4 Steps to Increase Visibility for Your Data Project 
description: Whether you have invested years into statistics, or are just getting started, presenting research projects on GitHub can be intimidating. Here are some tips that can get your work out there and in front of recruiters.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman