title: Statistics and Data Science Projects
description: Organized summaries of Jackson Passey's projects 
email: jxnpass@gmail.com

github:
  is_project_page: true
  owner_url: https://github.com/jxnpass
  owner_name: Jackson Passey

google_analytics:
theme: jekyll-theme-cayman