title: 5 Best Practices to Increase Visibility for Your Data Project 
description: Whether you have invested years into statistics, or are just dipping your toes, presenting research projects on GitHub can be intimidating. Here are some tips that helped me get organized.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman